= https://github.com/fekir/stylistic_guidelines[Styling Guidelines]


== Braces style
I use mostly the following style

* The opening left brace is at the end of the line beginning the compound statement
* The closing right brace is alone on a line, unless followed by the keywords "else" or "while", indented to the same column as the beginning of the compound statement.
* Every compound statement should have a pair of braces.

[source,c++]
----
class foo{
	private int a;

	foo(){
		a = 0;
	}

	int get(int b, int c){
		for(int i = 0; i < c; ++i){
			if(i < b){
				bar(i);
			} else {
				bar(i);
				bar(b);
			}
		}
		switch(a){
			case 1:
				bar(1);
				break;
			case 2:{
				bar(2);
				break;
			}
			case 3:
			default:
				bar(3);
				break;
		}
		return a;
	}
}
----

If the statement is short enough we may write the opening and closing brace on the same line

[source,c++]
----
if(p==nullptr){ throw std::runtime_error("null pointer!")}
----


The downside of this indentation style is the asymmetry between the opening and the closing braces. Alternatively you could write the opening brace on the next line in the same column

[source,c++]
----
class foo
{
	private int a;

	foo()
	{
		a = 0;
	}

	int get(int b, int c)
	{
		for(int i = 0; i < c; ++i)
		{
			if(i < b)
			{
				bar(i);
			}
			else
			{
				bar(i);
				bar(b);
			}
		}
		switch(a)
		{
			case 1:
				bar(1);
				break;
			case 2:
			{
				bar(2);
				break;
			}
			case 3:
			default:
				bar(3);
				break;
		}
		return a;
	}
}
----

Now the code is more hard to read since there are too lines without statements.
If your code is too dense, simply add some empty lines instead of moving the braces and change the style of the code.


== Indentation
A proper indentation will make the code easier to read and understandable. In my opinion, an indentation of 3-4 unit points is perfect. Most people will probably agree on 4 unit points, but I know some people will prefer to use only 2 unit points, and others 8 unit points.

In large sections of code containing many compound statements nested on many levels of indentation, it's easy to lose track of the block boundary, so you may prefer using large blocks of indentation. You also have to consider that your monitor has a maximum number of characters that it can display on one line. If you are using an IDE that has a lateral menu providing other information, you'll probably have between 80 and 180 characters.

Using 8 spaces would give us the following snippet. In my opinion the code is more difficult to read, because there is to much blank space

[source,c++]
----
class foo {
        void bar(int b, int c){
                for (int i = 0; i < c; ++i){
                        if (i < b){
                                baz(i);
                        }
                }
        }
}
----

Whereas using only two spaces will make the code too dense and I might miss some indentation when reading it

[source,c++]
----
class foo{
  int get(int b, int c){
    for(int i = 0; i < c; ++i){
      if(i < b){
        bar(i);
      } else {
        bar(i);
        bar(b);
      }
    }
    switch(a){
      case 1:
        bar(1);
        break;
      case 2:{
        bar(2);
        break;
      }
      case 3:
      default:
        bar(3);
        break;
    }
    return a;
  }
}
----

With the use of tabs instead of spaces, developers can choose how much to indent the code. Every tab should be equal to one logical indentation. At this point most people confuse indentation with alignment; you should use tabs for indenting your code, and spaces for aligning it. It is important to make this distinction, or your code might get mixed up; in the following example tabs have been replaced with an underscore and spaces a minus, to highlight the difference:

[source]
----
function(){
____verylongfunction(___verylongparam1,
________________________verylongparam1,
________________________verylongparam1
____)
}
----

and

[source]
----
function(){
____verylongfunction(-verylongparam1,
____------------------verylongparam1,
____------------------verylongparam1
____)
}
----

If someone sets the width of the tab to 3 units instead of 4, he will see

[source]
----
function(){
____verylongfunction(_verylongparam1,
__________________verylongparam1,
__________________verylongparam1
___)
}
----

and

[source]
----
function(){
___verylongfunction(-verylongparam1,
___------------------verylongparam1,
___------------------verylongparam1
___)
}
----

In the examples where the tab character was also used for alignment, the code seems to be aligned incorrectly .

Since you normally do not change the width of the tab, those error may never get spotted unless someone else is working on the same code. Most editors have an option for displaying tabs and white spaces, consider enabling it since it may help a lot for avoiding these type of errors.

If you are unsure, use tabs, it's easier to convert them to spaces with any editor. It's not that easy the other way around, unless you are using an editor with good auto-formatting capabilities.


Notice that in https://www.python.org[python] and probably other languages, you have to use spaces for indentation (even if this is wrong!).
https://en.wikipedia.org/wiki/Whitespace_%28programming_language%29[Whitespace] is one of those languages where the difference between tabs and spaces is really important.

== Braces style (2)
Every if-clause should have corresponding braces since it makes code more robust (and easier to read) if someone copy-pastes it, if the indentation is wrong, or if someone adds another statement and didn't notice the braces where missing.

== Trimming
Every line should be right-trimmed, even if it doesn't change aesthetically (if you do not set your editor to show whitespace characters).
This also means that empty lines are not indented (or they wouldn't be really empty!)

== Line length
The maximum line length should be between 80 and 120 characters.

Most policies use 80 characters; the problem is that after indenting 3 or 4 times (namespace, class, function declaration, and a couple of branches), with an indentation of 4 character, you may have less than 60 characters left for writing your code.

Also when writing comments, maybe with a link to a webpage, 60 or less characters are very few.

All modern monitors are able to display 120 and more characters on one line; but most code does not take up that much space and too long lines are more difficult to read.

Nevertheless my experience shows that most code (80% and maybe more) fits into 80 characters. Most of the remaining code fits in 120 characters and is still readable since it is not that much. If it occupies more than 120 characters then it is mostly a constant string/array (that can be written on multiple lines), a comment (maybe a link), or some piece of code that can easily get refactored on multiple lines (maybe a function with a lot of parameters).


== Naming convention
Many languages are type safe (C++, Java, Rust, ...), some have added type safety (PHP), and some are not (Python). There are static analyzers for nearly all languages, so you should avoid the Systems Hungarian notation (prefix variable with its own type). The Apps Hungarian notation is on the other hand very good, since it encodes the logical data type. If you can also encode the logical data type in a type safe manner (for example a separate struct), you could drop the Hungarian notation completely, even if it could be harder to read and write code, since you may need to do more conversions.

A variable name should give the reader a hint about what you can or should do, given the content in that context. The type of the variable is already written in the declaration.

C and C++ do not have an official naming convention, whereas Java and Python have standard practices. You should firstly use the common/expected conventions, then add your own.

=== camelcase/PascalCase vs snake_case
The snake_case convention has following advantages:

* It's better for accessibility, screen readers (fortunately!) do not read out which letter are uppercase and which are not, but it'll read out the underscore character.
* Names should be easier to read, since some letter may be hard to distinguish, for example I and l, particularly if someone is not a native English speaker/reader
* In some languages (even if you should write you source code in English), there are no uppercase and lowercase symbols, for example in Japanese.
* Some programming languages are not case sensitive (Pascal for example), so you notation cannot be enforced by the compiler and it gets more difficult to be consistent; you may write HttpRequest the first time, and HTTPRequest the second time.
* You should never use case sensitive filenames, since some operating systems (Windows and Mac OS) do not handle the difference, this may not be possible with some programming languages, like Java.
The only disadvantage so far is that the string get's longer, but it is going to be that long, then the name is probably to long also in camelCase.

=== Name length
The length of the variable name should be proportional to the number of lines of code where it is used. If the scope is very narrow, there is no reason to use a long variable name since it can't be confused with many other.

There are also some standard conventions (at least for me) for some variable types

* indexes (inside for-loop) : i, j, k, l, ii, jj
* exceptions (when catching them): ex
* iterators (inside for-loop): it
* struct with destructor for closing resource/take action when exiting of scope (and no other functionality): _

== Length of function
Ideally you should be able to read the whole content of a function without scrolling.


== Spacing
White space should be used to enhance readability. It's very difficult create a generic rule when or why you should add a space somewhere.

I tend to use a space when using the operators +, -, *, /, ..., and after ';' for example
----
for(int i = 0; i < a; ++i)
----

and I do not put it after "for", "while", and "if" statements

== Parenthesis

=== Optional parenthesis
Optional parenthesis should be added when it helps to improve readability, for example
----
if( (a && b) || (c != d) )
----
may be better than (and makes you avoid errors with the precedence of the and and or operator)
----
if( a && b || c != d)
----
Do not exaggerate, since too many parenthesis will cause confusion.

=== Parenthesis after the return keyword
Avoid them since they are unnecessary. Some people add the to be consistent with the fact that they use parenthesis for calling a function but return it's the exact opposite of calling a function. Adding parenthesis after a return is just misleading.

== Comments
If possible use single-line comments, so that it is possible to wrap them in multi-line comments. Avoid

----
/* one-liner */
function(){
....
}
----

prefer
----
// one-liner
function(){

}
----

so that if you need to comment out temporarily a block of code, you do not need to resort to editor specific features for adding "//" on every line, adding them manually, or using other tools like macros.

As a corollary, prefer following doxygen syntax

----
/// this is valid doxygen
----

instead of

----
/**
 * This is also valid doxygen
 */
----

Most people tend to use multiline comment in C source code, even if single-line comments are available in ANSI C since 1999 (nearly 20 years).


== include/import order
Normally you need to define at the begin of the file which function/classes/headers you are going to use. AFAIK order does not really matter.
You should go from local to global, include local headers (or import local classes) first, and then the global ones.
In C++ you should write

[source,c++]
----
// file.cpp
#include "file.hpp"

// local, same project
#include "my_header.hpp"

// external libraries (ordered by importance/platform availability)
# include "lib.hpp"

// system (windows, posix, ...)
# include <windows.h>

// cstd
#include <cassert>
#include <cstring>

// std
#include <string>
#include <vector>
----

Including the corresponding header as first proves that you can include the header file without prerequisites (it's very annoying when some headers requires other headers to be included first).

Ordering headers make it's also easier to verify your dependencies.

== struct/class structure
You should omit the empty sections.
The constructors (and copy/move operators) should be grouped together and placed before the public methods (if they are public too).
You should define the member variables before the methods that use them.

In C++

[source,c++]
----
class my_class{
	private:
		bool is_active = false;
		std::string name;
		...
	public:
		my_class();

		std::string get_name();
		...
	private:
		// some private methods
}
----

In Java

[source,java]
----
class MyClass{
	private boolean isActive = false;
	private String name = "";
	...

	public MyClass(){}

	String getName(){
		return name;
	}

	private void privateMethod(){}
}
----

== Variable declaration
You should declare every variable separately, declaring more variable together should be avoided, since it can get misleading, for example:

----
char* p, q;
----
So simply don't do that.

You should also initialize your variable when you declare it. In most languages declaring and initializing is the same thing, but not in C and C++. Still, if there is no sensible value for your type, there should be no reason for declaring it. In some programming languages, like Pascal, you need to declare all your variables at the begin of the function, if you do not have that restriction, you should declare you variable just where you need them, doing so makes the code easier to read because

* Even if the function is very long (and you should avoid that) and the variable is only used in a couple of spaces, you can see it's type without using the Systems Hungarian notation.
* Even if the control flow gets complicated, you can be sure that the variable is initialized to a sensible value.
* Dependencies between variables are easier to spot.


== Repetitive code
Is error prone to write and annoying to read.
You should put repetitive code in functions, if it's code for initializing a class/struct, then put it in the constructor, if it's for freeing resources, put it in a destructor/finalizer.

Initializing a variable only once make's it more easy to reason about it's value/state, compare

----
string a;
get(a);
a.trim()
----

against (assuming you can change the signature of the "get" function)

----
string a = get().trim()
----

In C++ you can also use auto to avoid writing long identifiers for the variable type, for example the following two lines

[source,c++]
----
const auto cit = my_vector.cbegin();
const std::vector<std::string>::const_iterator cit = my_vector.cbegin();
----

have exactly the same meaning. If for some reason you can't use auto, you can use a typedef or using:

[source,c++]
----
using vec_strin_citer = std::vector<std::string>::const_iterator
const vec_strin_citer cit = my_vector.cbegin()
----

In Java you can use the diamond notation, following lines have exactly the same meaning:

[source,java]
----
Map<String, List<String>> anagrams = new HashMap<String, List<String>>();
Map<String, List<String>> anagrams = new HashMap<>();
----


== Number of parameters
Functions (or constructors) with to many parameters are difficult to read and use correctly.
Consider the following function (taken from https://msdn.microsoft.com/en-us/library/windows/desktop/ms632680(v=vs.85).aspx[msdn]):

[source, c++]
----
HWND CreateWindowEx(DWORD dwExStyle, LPCTSTR lpClassName, LPCTSTR lpWindowName, DWORD dwStyle, int x, int y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam);
----

The signature of the function alone is taking more than 180 characters, so we need to split it on multiple lines.

[source, c++]
----
HWND CreateWindowEx(
  DWORD dwExStyle,
  LPCTSTR lpClassName,
  LPCTSTR lpWindowName,
  DWORD dwStyle,
  int x,
  int y,
  int nWidth,
  int nHeight,
  HWND hWndParent,
  HMENU hMenu,
  HINSTANCE hInstance,
  LPVOID lpParam
);
----

The same problem appears when we want to use that function; we need to split it on multiple lines

[source, c++]
----
hwnd = CreateWindowEx(
        WS_EX_CLIENTEDGE,
        L"class name",
        L"title name,
        WS_OVERLAPPEDWINDOW,
        CW_USEDEFAULT, CW_USEDEFAULT, 240, 120,
        nullptr, nullptr, hInstance, nullptr);
----

but that does not improve the readability, without looking at the documentation or at the signature, if one simply reads the code where the function is used, he will not understand the meaning of most parameters, for example where nullptr or a number is passed. Of course you could save every parameter to a separate variable, for example

[source, c++]
----
const int x = CW_USEDEFAULT;
const int y = CW_USEDEFAULT;
const int width = 240;
const int height = 120;

const hwnd = CreateWindowEx(
        WS_EX_CLIENTEDGE,
        L"class name",
        L"title name",
        WS_OVERLAPPEDWINDOW,
        x, y, width, height,
        nullptr, nullptr, hInstance, nullptr);
----
But this process is error prone, and you need to write a lot more code.

A better solution is to simply write function that needs at most 3 or four parameters. You can always pass structures or classes to give the function more flexibility, and in this way (not in C) you can also define default values, for example:

[source, c++]
----
// declarations
struct CreateWindowExParam {
	DWORD dwExStyle = WS_EX_CLIENTEDGE;
	LPCTSTR lpClassName = nullptr;
	LPCTSTR lpWindowName = nullptr;
	DWORD dwStyle = WS_OVERLAPPEDWINDOW;
	HWND hWndParent = nullptr;
	HMENU hMenu = nullptr;
	HINSTANCE hInstance = nullptr;
	LPVOID lpParam = nullptr;
};

struct size_and_position {
	int x = CW_USEDEFAULT;
	int y = CW_USEDEFAULT;
	int width = CW_USEDEFAULT;
	int height = CW_USEDEFAULT;
};

HWND CreateWindowEx(const CreateWindowExParam& params, const size_and_position& s_p);

// usage
CreateWindowExParam params;
params.lpClassName = "class name";
params.lpWindowName = "windows name";
params.hInstance = hInstance;

size_and_position size_pos;
size_pos.width = 240;
size_pos.height = 120;

const hwnd = CreateWindowEx(params, size_pos);
----

By grouping together the parameters, we do not need to break a statement on multiple lines. For simple cases a struct is more than enough, for more complex cases you may provide a constructor for improving readability. In the declaration we could write

[source, c++]
----
HWND CreateWindowEx(const CreateWindowExParam&, const size_and_position&);
----
without loosing much information, whereas
[source, c++]
----
HWND CreateWindowEx(DWORD, LPCTSTR, LPCTSTR, DWORD, int, int, int, int, HWND, HMENU, HINSTANCE , LPVOID);
----
is more difficult to understand.
